### ISSUE TITLE
Can't use it to delete any files

### ISSUE THREAD

**Issue by 3ht7pud22ih9i5elvjkou** [zen-ham/force-delete#1]
Even can't remove a non-running file. How can I remove it? thanks.

**Comment by SashaIndustries** [comment]
I wanted to use this script to delete corrupted files as on an eternal drive I disabled read only for a folder only to find corrupt files, but this script cannot delete files on other drives I get the error below, its the same for even non-corrupted files. Works on C:/ but not on any other drive. Not sure if its meant to be adding two \\ or not.

Deleting E:\Media\Games\Game Managers\Steam\steamapps\common\Dawnlands\Dawnlands_Data\XGSDK-LOG\Force_Delete.reg
[WinError 267] The directory name is invalid: 'E:\\Media\\Games\\Game Managers\\Steam\\steamapps\\common\\Dawnlands\\Dawnlands_Data\\XGSDK-LOG\\Force_Delete.reg'
Failed, finding process
First pass
Second pass

**Comment by Nelethor** [comment]
If anyone in the future wants to uninstall this script, just delete all its files and

> Windows Registry Editor Version 5.00
> 
> ; Remove Force_Delete entries from the registry
> 
> [-HKEY_CLASSES_ROOT\*\shell\Force_Delete]
> [-HKEY_CLASSES_ROOT\*\shell\runas]
> [-HKEY_CLASSES_ROOT\Directory\shell\Force_Delete]
> 
> ; This registry file will delete the context menu items for Force Delete.
> 

put this into .txt, save as .reg and run it.

**Comment by zen-ham** [comment]
My apologies, as I'm no longer maintaining this project. If you wish to uninstall the script, use the code provided by @Nelethor.
